# Form implementation generated from reading ui file 'e:\0001_Work_New\012_ZGHK\QT_ERP_Python\ERP_Python_qt\Addons\BaseAddons\MainWindow\Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErpWidget(object):
    def setupUi(self, ErpWidget):
        ErpWidget.setObjectName("ErpWidget")
        ErpWidget.resize(500, 300)
        self.username_label = QtWidgets.QLabel(parent=ErpWidget)
        self.username_label.setGeometry(QtCore.QRect(120, 110, 54, 41))
        self.username_label.setStyleSheet("font: 12pt \"站酷高端黑\";")
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(parent=ErpWidget)
        self.password_label.setGeometry(QtCore.QRect(120, 160, 54, 41))
        self.password_label.setStyleSheet("font: 12pt \"站酷高端黑\";")
        self.password_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_label.setIndent(-1)
        self.password_label.setObjectName("password_label")
        self.system_name = QtWidgets.QLabel(parent=ErpWidget)
        self.system_name.setGeometry(QtCore.QRect(130, 30, 231, 41))
        self.system_name.setStyleSheet("font: 12pt \"站酷高端黑\";")
        self.system_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.system_name.setObjectName("system_name")
        self.username = QtWidgets.QLineEdit(parent=ErpWidget)
        self.username.setGeometry(QtCore.QRect(200, 110, 150, 41))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=ErpWidget)
        self.password.setGeometry(QtCore.QRect(200, 160, 150, 41))
        self.password.setObjectName("password")
        self.loginButton = QtWidgets.QPushButton(parent=ErpWidget)
        self.loginButton.setGeometry(QtCore.QRect(150, 240, 200, 37))
        self.loginButton.setStyleSheet("font: 16pt \"站酷高端黑\";\n"
"text-decoration: underline;")
        self.loginButton.setObjectName("loginButton")
        self.password_label.raise_()
        self.system_name.raise_()
        self.username_label.raise_()
        self.username.raise_()
        self.password.raise_()
        self.loginButton.raise_()

        self.retranslateUi(ErpWidget)
        QtCore.QMetaObject.connectSlotsByName(ErpWidget)

    def retranslateUi(self, ErpWidget):
        _translate = QtCore.QCoreApplication.translate
        ErpWidget.setWindowTitle(_translate("ErpWidget", "用户登录"))
        self.username_label.setText(_translate("ErpWidget", "用户"))
        self.password_label.setText(_translate("ErpWidget", "密码"))
        self.system_name.setText(_translate("ErpWidget", "ZGHK 管理系统"))
        self.loginButton.setText(_translate("ErpWidget", "登录"))
